In [45]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix
import seaborn as sns  

from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("spam_ham_dataset.csv")

In [6]:
df.describe()

        Unnamed: 0    label_num
count  5171.000000  5171.000000
mean   2585.000000     0.289886
std    1492.883452     0.453753
min       0.000000     0.000000
25%    1292.500000     0.000000
50%    2585.000000     0.000000
75%    3877.500000     1.000000
max    5170.000000     1.000000

In [7]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [8]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [9]:
df['label'].value_counts()

label
ham     3672
spam    1499
Name: count, dtype: int64

In [10]:
df['label'].value_counts(normalize=True) * 100

label
ham     71.01141
spam    28.98859
Name: proportion, dtype: float64

In [11]:
print(df.isnull().sum())

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [15]:
df.duplicated(subset=['text']).sum()

Duplicates: 0

In [14]:
 df =df.drop_duplicates(subset=['text'])

In [21]:
df['char_count'] = df['text'].apply(len)
print(df.groupby('label')
['char_count'].mean())

label
ham      994.939394
spam    1249.326265
Name: char_count, dtype: float64

In [23]:
X = df['text']
y = df['label_num']

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42,stratify = y)

In [27]:
print(f"Emails for Training: {len(X_train)}")

Emails for Training: 3994

In [28]:
print(f"Emails for Testing:  {len(X_test)}")

Emails for Testing:  999

In [46]:
model = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english', lowercase=True)),
    ('classifier', LogisticRegression(max_iter=1000))
])

In [47]:
model.fit(X_train, y_train)
print("Model trained successfully!")

Model trained successfully!

In [48]:
y_pred = model.predict(X_test)

In [49]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

Accuracy: 0.9819819819819819

Classification Report:
               precision    recall  f1-score   support

         Ham       1.00      0.98      0.99       706
        Spam       0.95      0.99      0.97       293

    accuracy                           0.98       999
   macro avg       0.97      0.99      0.98       999
weighted avg       0.98      0.98      0.98       999

In [40]:
sample_emails = [
    "Hey John, can you send me the slides for tomorrow's project meeting?",
    "URGENT! You have won a $1,000,000 cash prize. Click here to claim your reward immediately!"
]
predictions = model.predict(sample_emails)

for email, pred in zip(sample_emails, predictions):
    result = "SPAM 🚨" if pred == 1 else "HAM (Legitimate) ✅"
    print(f"Email: '{email}'")
    print(f"Prediction: {result}\n")

Email: 'Hey John, can you send me the slides for tomorrow's project meeting?'
Prediction: HAM (Legitimate) ✅

Email: 'URGENT! You have won a $1,000,000 cash prize. Click here to claim your reward immediately!'
Prediction: HAM (Legitimate) ✅

In [43]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[702   4]
 [ 62 231]]